/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProdottiRouteImport } from './routes/_authenticated/prodotti'
import { Route as AuthenticatedOrdiniRouteImport } from './routes/_authenticated/ordini'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProdottiRoute = AuthenticatedProdottiRouteImport.update({
  id: '/prodotti',
  path: '/prodotti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdiniRoute = AuthenticatedOrdiniRouteImport.update({
  id: '/ordini',
  path: '/ordini',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ordini': typeof AuthenticatedOrdiniRoute
  '/prodotti': typeof AuthenticatedProdottiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ordini': typeof AuthenticatedOrdiniRoute
  '/prodotti': typeof AuthenticatedProdottiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ordini': typeof AuthenticatedOrdiniRoute
  '/_authenticated/prodotti': typeof AuthenticatedProdottiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/ordini' | '/prodotti'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/ordini' | '/prodotti'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ordini'
    | '/_authenticated/prodotti'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prodotti': {
      id: '/_authenticated/prodotti'
      path: '/prodotti'
      fullPath: '/prodotti'
      preLoaderRoute: typeof AuthenticatedProdottiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordini': {
      id: '/_authenticated/ordini'
      path: '/ordini'
      fullPath: '/ordini'
      preLoaderRoute: typeof AuthenticatedOrdiniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrdiniRoute: typeof AuthenticatedOrdiniRoute
  AuthenticatedProdottiRoute: typeof AuthenticatedProdottiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrdiniRoute: AuthenticatedOrdiniRoute,
  AuthenticatedProdottiRoute: AuthenticatedProdottiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
