/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracciaSlugRouteImport } from './routes/traccia.$slug'
import { Route as LidoSlugRouteImport } from './routes/lido.$slug'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedQrcodeRouteImport } from './routes/_authenticated/qrcode'
import { Route as AuthenticatedProdottiRouteImport } from './routes/_authenticated/prodotti'
import { Route as AuthenticatedOrdiniRouteImport } from './routes/_authenticated/ordini'
import { Route as AuthenticatedMappaRouteImport } from './routes/_authenticated/mappa'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedConfigurazioneLidoRouteImport } from './routes/_authenticated/configurazione-lido'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracciaSlugRoute = TracciaSlugRouteImport.update({
  id: '/traccia/$slug',
  path: '/traccia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LidoSlugRoute = LidoSlugRouteImport.update({
  id: '/lido/$slug',
  path: '/lido/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrcodeRoute = AuthenticatedQrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdottiRoute = AuthenticatedProdottiRouteImport.update({
  id: '/prodotti',
  path: '/prodotti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdiniRoute = AuthenticatedOrdiniRouteImport.update({
  id: '/ordini',
  path: '/ordini',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMappaRoute = AuthenticatedMappaRouteImport.update({
  id: '/mappa',
  path: '/mappa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigurazioneLidoRoute =
  AuthenticatedConfigurazioneLidoRouteImport.update({
    id: '/configurazione-lido',
    path: '/configurazione-lido',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/configurazione-lido': typeof AuthenticatedConfigurazioneLidoRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/mappa': typeof AuthenticatedMappaRoute
  '/ordini': typeof AuthenticatedOrdiniRoute
  '/prodotti': typeof AuthenticatedProdottiRoute
  '/qrcode': typeof AuthenticatedQrcodeRoute
  '/report': typeof AuthenticatedReportRoute
  '/lido/$slug': typeof LidoSlugRoute
  '/traccia/$slug': typeof TracciaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/configurazione-lido': typeof AuthenticatedConfigurazioneLidoRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/mappa': typeof AuthenticatedMappaRoute
  '/ordini': typeof AuthenticatedOrdiniRoute
  '/prodotti': typeof AuthenticatedProdottiRoute
  '/qrcode': typeof AuthenticatedQrcodeRoute
  '/report': typeof AuthenticatedReportRoute
  '/lido/$slug': typeof LidoSlugRoute
  '/traccia/$slug': typeof TracciaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/configurazione-lido': typeof AuthenticatedConfigurazioneLidoRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/mappa': typeof AuthenticatedMappaRoute
  '/_authenticated/ordini': typeof AuthenticatedOrdiniRoute
  '/_authenticated/prodotti': typeof AuthenticatedProdottiRoute
  '/_authenticated/qrcode': typeof AuthenticatedQrcodeRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/lido/$slug': typeof LidoSlugRoute
  '/traccia/$slug': typeof TracciaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/configurazione-lido'
    | '/impostazioni'
    | '/mappa'
    | '/ordini'
    | '/prodotti'
    | '/qrcode'
    | '/report'
    | '/lido/$slug'
    | '/traccia/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/configurazione-lido'
    | '/impostazioni'
    | '/mappa'
    | '/ordini'
    | '/prodotti'
    | '/qrcode'
    | '/report'
    | '/lido/$slug'
    | '/traccia/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authenticated/configurazione-lido'
    | '/_authenticated/impostazioni'
    | '/_authenticated/mappa'
    | '/_authenticated/ordini'
    | '/_authenticated/prodotti'
    | '/_authenticated/qrcode'
    | '/_authenticated/report'
    | '/lido/$slug'
    | '/traccia/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  LidoSlugRoute: typeof LidoSlugRoute
  TracciaSlugRoute: typeof TracciaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traccia/$slug': {
      id: '/traccia/$slug'
      path: '/traccia/$slug'
      fullPath: '/traccia/$slug'
      preLoaderRoute: typeof TracciaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lido/$slug': {
      id: '/lido/$slug'
      path: '/lido/$slug'
      fullPath: '/lido/$slug'
      preLoaderRoute: typeof LidoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qrcode': {
      id: '/_authenticated/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof AuthenticatedQrcodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prodotti': {
      id: '/_authenticated/prodotti'
      path: '/prodotti'
      fullPath: '/prodotti'
      preLoaderRoute: typeof AuthenticatedProdottiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordini': {
      id: '/_authenticated/ordini'
      path: '/ordini'
      fullPath: '/ordini'
      preLoaderRoute: typeof AuthenticatedOrdiniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mappa': {
      id: '/_authenticated/mappa'
      path: '/mappa'
      fullPath: '/mappa'
      preLoaderRoute: typeof AuthenticatedMappaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configurazione-lido': {
      id: '/_authenticated/configurazione-lido'
      path: '/configurazione-lido'
      fullPath: '/configurazione-lido'
      preLoaderRoute: typeof AuthenticatedConfigurazioneLidoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfigurazioneLidoRoute: typeof AuthenticatedConfigurazioneLidoRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedMappaRoute: typeof AuthenticatedMappaRoute
  AuthenticatedOrdiniRoute: typeof AuthenticatedOrdiniRoute
  AuthenticatedProdottiRoute: typeof AuthenticatedProdottiRoute
  AuthenticatedQrcodeRoute: typeof AuthenticatedQrcodeRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfigurazioneLidoRoute: AuthenticatedConfigurazioneLidoRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedMappaRoute: AuthenticatedMappaRoute,
  AuthenticatedOrdiniRoute: AuthenticatedOrdiniRoute,
  AuthenticatedProdottiRoute: AuthenticatedProdottiRoute,
  AuthenticatedQrcodeRoute: AuthenticatedQrcodeRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  LidoSlugRoute: LidoSlugRoute,
  TracciaSlugRoute: TracciaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
